import test from 'node:test';
import assert from 'node:assert/strict';
import { applyCalibration } from '../src/domain/calibration/apply.ts';
import { synchronizeSamples } from '../src/domain/clock/synchronize.ts';
import { analyzeExperiment } from '../src/application/analysis-service.ts';
import { precheckExperiment } from '../src/application/precheck-service.ts';
import { createServer } from '../src/http/server.ts';
import { periodogram } from '../src/domain/signal/spectrum.ts';
import type { RawSample, CalibrationProfile } from '../src/domain/types.ts';

const calibration: CalibrationProfile = { profileId: 'cal-1', channelId: 'ch-a', validFromNs: 0, adcScale: 2, iOffset: 0.1, qOffset: -0.2, gainCorrection: 1, phaseCorrectionRad: 0, temperatureCoefficientPerK: 0, referenceTemperatureK: 0.02, systematicUncertainty: 0.01, sampleUncertainty: 0.001 };
function sample(index: number, channelId = 'ch-a'): RawSample { return { captureId: `${channelId}-${index}`, experimentId: 'exp-1', channelId, role: 'readout-i', triggerId: `t-${Math.floor(index / 4)}`, timestampNs: index * 1_000_000, receivedAtNs: index * 1_000_000 + 100, sequence: index, sampleRateHz: 1_000, i: Math.cos(index / 4) + 0.1, q: Math.sin(index / 4) - 0.2, quality: 'good' }; }

test('synchronization removes exact duplicates but rejects conflicting capture ids', () => { const first = sample(1); assert.equal(synchronizeSamples([first, { ...first }]).droppedSamples, 1); assert.throws(() => synchronizeSamples([first, { ...first, i: 4 }]), /conflicting payloads/); });
test('calibration applies offset, gain and phase while preserving profile identity', () => { const calibrated = applyCalibration([sample(0)], [calibration]); assert.equal(calibrated[0].calibrationProfileId, 'cal-1'); assert.ok(calibrated[0].uncertainty > calibration.systematicUncertainty); });
test('periodogram exposes a stable frequency axis', () => { const bins = periodogram([{ startNs: 0, endNs: 8, sampleRateHz: 8, values: [1, 0, -1, 0, 1, 0, -1, 0], weights: Array(8).fill(1) }], 4); assert.equal(bins[1].frequencyHz, 1); assert.ok(bins[2].power > bins[1].power); });
test('full analysis returns reproducible digest and fitted metrics', () => { const input = { experimentId: 'exp-1', kind: 't1' as const, samples: Array.from({ length: 32 }, (_, index) => sample(index)), calibrations: [calibration], analysis: { windowSize: 16 } }; const first = analyzeExperiment(input); const second = analyzeExperiment(input); assert.equal(first.inputDigest, second.inputDigest); assert.equal(first.metrics.sampleCount, 32); assert.ok(first.primarySpectrum.length > 0); });

test('precheck accepts fully covered data as ready', () => { const report = precheckExperiment({ experimentId: 'exp-1', kind: 't1', samples: Array.from({ length: 32 }, (_, index) => sample(index)), calibrations: [calibration] }); assert.equal(report.verdict, 'ready'); assert.deepEqual(report.issues, []); assert.equal(report.totals.usableSamples, 32); assert.equal(report.channels[0].usableSamples, 32); });
test('precheck does not modify the request', () => { const request = { experimentId: 'exp-1', kind: 't1' as const, samples: [sample(0), { ...sample(1), quality: 'invalid' as const }], calibrations: [calibration] }; const snapshot = JSON.stringify(request); const freeze = (value: unknown): void => { if (value && typeof value === 'object') { Object.values(value).forEach(freeze); Object.freeze(value); } }; freeze(request); const report = precheckExperiment(request); assert.equal(report.totals.invalidSamples, 1); assert.equal(JSON.stringify(request), snapshot); });
test('precheck reports missing calibration by channel and time range', () => { const samples = [...Array.from({ length: 8 }, (_, index) => sample(index)), ...Array.from({ length: 4 }, (_, index) => sample(index + 8, 'ch-b'))]; const report = precheckExperiment({ experimentId: 'exp-1', kind: 't1', samples, calibrations: [calibration] }); assert.equal(report.verdict, 'fixable'); const missing = report.issues.find((issue) => issue.category === 'calibration-missing'); assert.equal(missing?.channelId, 'ch-b'); assert.equal(missing?.sampleCount, 4); assert.equal(missing?.startNs, 8_000_000); assert.equal(missing?.endNs, 11_000_000); });
test('precheck distinguishes role mismatch from missing calibration', () => { const roleProfile = { ...calibration, profileId: 'cal-role', role: 'readout-q' as const }; const report = precheckExperiment({ experimentId: 'exp-1', kind: 't1', samples: Array.from({ length: 4 }, (_, index) => sample(index)), calibrations: [roleProfile] }); assert.equal(report.verdict, 'abort'); assert.equal(report.issues[0].category, 'role-mismatch'); assert.deepEqual(report.issues[0].profileIds, ['cal-role']); });
test('precheck flags overlapping calibration validity where data is ambiguous', () => { const first = { ...calibration, profileId: 'cal-1', validFromNs: 0, validToNs: 20_000_000 }; const second = { ...calibration, profileId: 'cal-2', validFromNs: 10_000_000 }; const report = precheckExperiment({ experimentId: 'exp-1', kind: 't1', samples: Array.from({ length: 32 }, (_, index) => sample(index)), calibrations: [first, second] }); const overlap = report.issues.find((issue) => issue.category === 'validity-overlap'); assert.equal(report.verdict, 'fixable'); assert.equal(overlap?.sampleCount, 10); assert.deepEqual(overlap?.profileIds, ['cal-1', 'cal-2']); assert.equal(overlap?.startNs, 10_000_000); assert.equal(overlap?.endNs, 19_000_000); });
test('precheck applies default temperature and rejects invalid temperature corrections', () => { const profile = { ...calibration, temperatureCoefficientPerK: -0.5, referenceTemperatureK: 10 }; const samples = [...Array.from({ length: 8 }, (_, index) => sample(index)), ...Array.from({ length: 4 }, (_, index) => ({ ...sample(index + 8), temperatureK: 12 }))]; const report = precheckExperiment({ experimentId: 'exp-1', kind: 't1', samples, calibrations: [profile] }); const thermal = report.issues.find((issue) => issue.category === 'temperature-correction-invalid'); assert.equal(report.verdict, 'fixable'); assert.equal(thermal?.sampleCount, 4); assert.equal(report.totals.usableSamples, 8); });
test('precheck handles mixed valid and invalid samples', () => { const samples = Array.from({ length: 16 }, (_, index) => (index % 4 === 0 ? { ...sample(index), quality: 'invalid' as const } : sample(index))); const report = precheckExperiment({ experimentId: 'exp-1', kind: 't1', samples, calibrations: [calibration] }); assert.equal(report.verdict, 'fixable'); assert.equal(report.totals.invalidSamples, 4); assert.equal(report.totals.usableSamples, 12); assert.equal(report.issues[0].category, 'invalid-sample'); });
test('precheck aborts when data is completely unusable', () => { assert.equal(precheckExperiment({ experimentId: 'exp-1', kind: 't1', samples: [], calibrations: [calibration] }).verdict, 'abort'); assert.equal(precheckExperiment({ experimentId: 'exp-1', kind: 't1', samples: [sample(0), sample(1)], calibrations: [] }).verdict, 'abort'); const allInvalid = precheckExperiment({ experimentId: 'exp-1', kind: 't1', samples: [{ ...sample(0), quality: 'invalid' as const }, { ...sample(1), quality: 'invalid' as const }], calibrations: [calibration] }); assert.equal(allInvalid.verdict, 'abort'); assert.equal(allInvalid.totals.usableSamples, 0); });
test('precheck follows samples across calibration intervals', () => { const first = { ...calibration, profileId: 'cal-early', validFromNs: 0, validToNs: 16_000_000 }; const second = { ...calibration, profileId: 'cal-late', validFromNs: 16_000_000 }; const report = precheckExperiment({ experimentId: 'exp-1', kind: 't1', samples: Array.from({ length: 32 }, (_, index) => sample(index)), calibrations: [first, second] }); assert.equal(report.verdict, 'ready'); assert.equal(report.totals.usableSamples, 32); });
test('precheck endpoint returns a report and reuses the HTTP error format', async () => { const server = createServer(); await new Promise<void>((resolve) => server.listen(0, '127.0.0.1', resolve)); const address = server.address(); const port = typeof address === 'object' && address ? address.port : 0; const post = (body: string) => fetch(`http://127.0.0.1:${port}/v1/experiments/precheck`, { method: 'POST', headers: { 'content-type': 'application/json' }, body }); try { const malformed = await post('{broken'); assert.equal(malformed.status, 400); assert.equal((await malformed.json()).error.code, 'INVALID_JSON'); const empty = await post('{}'); assert.equal(empty.status, 422); assert.equal((await empty.json()).error.code, 'INVALID_EXPERIMENT_ID'); const ok = await post(JSON.stringify({ experimentId: 'exp-1', kind: 't1', samples: Array.from({ length: 8 }, (_, index) => sample(index)), calibrations: [calibration] })); assert.equal(ok.status, 200); assert.equal((await ok.json()).verdict, 'ready'); } finally { server.close(); } });
